name: coffea_suite_frontend
description: "Coffea Suite POS and Inventory Management System"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # --- State Management ---
  flutter_bloc: ^8.1.5
  equatable: ^2.0.7

  # --- Local Database ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # --- Networking & API ---
  dio: ^5.4.3+1
  connectivity_plus: ^7.0.0

  # --- Utils ---
  shared_preferences: ^2.5.3
  uuid: ^4.3.3
  collection: ^1.18.0
  provider: ^6.1.5+1
  intl: ^0.20.2

  # --- Font ---
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/data/ingredients_list.json
    - assets/data/products_list.json
    - assets/data/ingredients_usage.json
    - assets/images/Americano.png
    - assets/images/Blueberry.png
    - assets/images/Caramel_Machiato.png
    - assets/images/Coffee_Jelly.png
    - assets/images/Dirty_Matcha.png
    - assets/images/Dulce_de_Leche.png
    - assets/images/Flat_White.png
    - assets/images/Greeny_Apple.png
    - assets/images/Hazelnut_Latte.png
    - assets/images/Honey_Peach.png
    - assets/images/Latte.png
    - assets/images/Mango_Twist.png
    - assets/images/Matcha.png
    - assets/images/Milky_Matcha.png
    - assets/images/Milky_Strawberry.png
    - assets/images/Mocha_JavaChips.png
    - assets/images/Mocha_Latte.png
    - assets/images/Signature_Cocoa.png
    - assets/images/Spanish_Latte.png
    - assets/images/Strawberry_Lime.png
    - assets/images/Strawberry_Matcha.png
    - assets/images/Strawberry.png
    - assets/images/Vanilla_Latte.png
    - assets/images/White_Mocha_Latte.png
    - assets/images/Sisig.png
    - assets/images/Baby_Back_Ribs.png
    - assets/images/Chicken_and_Fries.png
    - assets/images/Cheesy_Burger.png
    - assets/images/Cookies.png
    - assets/images/Slice_of_Cake.png
    - assets/images/Cup_of_Coffee.png
    - assets/images/meals.png
    - assets/images/p-and-d.png
