name: coffea_suite_frontend
description: "Coffea Suite POS and Inventory Management System"
publish_to: 'none'
version: 1.2.3+6

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # --- State Management ---
  flutter_bloc: ^8.1.5
  equatable: ^2.0.7

  # --- Local Database ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # --- Networking & API ---
  dio: ^5.4.3+1
  connectivity_plus: ^7.0.0
  supabase_flutter: ^2.0.0

  # --- Utils ---
  shared_preferences: ^2.5.3
  uuid: ^4.3.3
  collection: ^1.18.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  bcrypt: ^1.1.3
  fl_chart: ^0.69.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/data/ingredients_list.json
    - assets/data/products_list.json
    - assets/data/ingredients_usage.json
    - assets/data/users_list.json
